WITH RECURSIVE Generation AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION

    SELECT e.ID, e.PARENT_ID, g.GEN + 1 AS GEN
    FROM ECOLI_DATA e
    JOIN Generation g ON e.PARENT_ID = g.ID
)
SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM Generation g
WHERE NOT EXISTS (SELECT 1 FROM ECOLI_DATA e WHERE e.PARENT_ID = g.ID)
GROUP BY GEN
ORDER BY GENERATION ASC