SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM member_profile
WHERE gender = 'W'
AND tlno IS NOT NULL
AND MONTH(date_of_birth) = 3
ORDER BY member_id ASC;