WITH Rental_Count AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE EXTRACT(YEAR FROM START_DATE) = 2022
    AND EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
),
Monthly_Rental AS (
    SELECT 
        EXTRACT(MONTH FROM START_DATE) AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE EXTRACT(YEAR FROM START_DATE) = 2022
    AND EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
    AND CAR_ID IN (
        SELECT CAR_ID 
        FROM Rental_Count
    )
    GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
)
SELECT *
FROM Monthly_Rental
ORDER BY MONTH ASC, CAR_ID DESC